import JSZip from 'jszip';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Header,
  Footer,
  AlignmentType,
  HeadingLevel,
} from 'docx';
import { saveAs } from 'file-saver';

import type { Message } from './api';
import { getAuthHeaders } from './api';
import { getTemplateById } from './documentLibrary';
import type { DocumentTemplate } from './documentLibrary';
import { formatResponse } from './formatResponse';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface DocumentPackData {
  summary: string;
  actionChecklist: string[];
  documents: Array<{
    templateId: string;
    title: string;
    filledFields: Record<string, string>;
  }>;
}

interface GeneratedDoc {
  filename: string;
  title: string;
  category: string;
  blob: Blob;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\-. ]/g, '').replace(/\s+/g, '_');
}

function formatDate(date: Date): string {
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
}

function formatDateFilename(date: Date): string {
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  return `${year}-${month}-${day}`;
}

/**
 * Try to parse JSON from a string that may be wrapped in markdown fences.
 */
function parseJsonSafe(raw: string): DocumentPackData {
  let cleaned = raw.trim();

  // Strip markdown code fences if present
  const fenceMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) {
    cleaned = fenceMatch[1].trim();
  }

  return JSON.parse(cleaned) as DocumentPackData;
}

// ---------------------------------------------------------------------------
// DOCX generation helpers
// ---------------------------------------------------------------------------

/**
 * Creates a paragraph with [INSERT: ...] fields highlighted in bold red.
 */
function createFieldParagraph(
  text: string,
  options?: { bold?: boolean; size?: number }
): Paragraph {
  const parts = text.split(/(\[INSERT:[^\]]+\])/g);
  const children: TextRun[] = parts.map((part) => {
    if (part.match(/^\[INSERT:/)) {
      return new TextRun({
        text: part,
        bold: true,
        color: 'CC0000',
        font: 'Arial',
        size: options?.size || 24,
      });
    }
    return new TextRun({
      text: part,
      bold: options?.bold || false,
      font: 'Arial',
      size: options?.size || 24,
    });
  });
  return new Paragraph({ children });
}

function buildDocxFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Document generated by SIT-HR - Review before use - Not legal advice',
            size: 16, // 8pt
            color: '999999',
            font: 'Arial',
          }),
        ],
        alignment: AlignmentType.CENTER,
      }),
    ],
  });
}

function buildDocxFromTemplate(
  template: DocumentTemplate,
  title: string,
  filledFields: Record<string, string>,
  dateStr: string
): Document {
  const bodyChildren: Paragraph[] = [];

  // Document title
  bodyChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          font: 'Arial',
          size: 28, // 14pt
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    })
  );

  // Organisation name
  bodyChildren.push(
    createFieldParagraph('[INSERT: Organisation name]', { bold: true, size: 24 })
  );

  // Date
  bodyChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Date: ${dateStr}`,
          font: 'Arial',
          size: 24,
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Horizontal rule (blank line separator)
  bodyChildren.push(
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: '_______________________________________________',
          font: 'Arial',
          size: 24,
          color: 'CCCCCC',
        }),
      ],
    })
  );

  // Render each template section
  for (const section of template.sections) {
    if (section.heading) {
      bodyChildren.push(
        new Paragraph({
          text: section.heading,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        })
      );
    }

    for (const para of section.paragraphs) {
      // Replace filled fields in the paragraph text
      let processedText = para;
      for (const [field, value] of Object.entries(filledFields)) {
        const placeholder = `[INSERT: ${field}]`;
        processedText = processedText.split(placeholder).join(value);
      }
      bodyChildren.push(createFieldParagraph(processedText));
      bodyChildren.push(new Paragraph({ spacing: { after: 100 } }));
    }
  }

  return new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: title,
                    bold: true,
                    font: 'Arial',
                    size: 18, // 9pt
                    color: '666666',
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: buildDocxFooter(),
        },
        children: bodyChildren,
      },
    ],
  });
}

function buildGenericDocx(
  title: string,
  filledFields: Record<string, string>,
  dateStr: string
): Document {
  const bodyChildren: Paragraph[] = [];

  bodyChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          font: 'Arial',
          size: 28,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    })
  );

  bodyChildren.push(
    createFieldParagraph('[INSERT: Organisation name]', { bold: true, size: 24 })
  );

  bodyChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Date: ${dateStr}`,
          font: 'Arial',
          size: 24,
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Render filled fields as content
  if (Object.keys(filledFields).length > 0) {
    bodyChildren.push(
      new Paragraph({
        text: 'Document Details',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );

    for (const [field, value] of Object.entries(filledFields)) {
      bodyChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `${field}: `,
              bold: true,
              font: 'Arial',
              size: 24,
            }),
            new TextRun({
              text: value,
              font: 'Arial',
              size: 24,
            }),
          ],
          spacing: { after: 100 },
        })
      );
    }
  }

  return new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: title,
                    bold: true,
                    font: 'Arial',
                    size: 18,
                    color: '666666',
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: buildDocxFooter(),
        },
        children: bodyChildren,
      },
    ],
  });
}

// ---------------------------------------------------------------------------
// PDF helpers: emoji stripping, markdown parsing, rendering
// ---------------------------------------------------------------------------

function stripEmoji(text: string): string {
  return text
    .replace(/🟢/g, '[LOW]')
    .replace(/🟠/g, '[MEDIUM]')
    .replace(/🔴🔴/g, '[CRITICAL]')
    .replace(/🔴/g, '[HIGH]')
    .replace(/⚠️/g, '[WARNING]')
    .replace(/✅/g, '[YES]')
    .replace(/❌/g, '[NO]')
    .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')
    .replace(/[\u{2600}-\u{27BF}]/gu, '');
}

interface MarkdownBlock {
  type: 'h1' | 'h2' | 'h3' | 'paragraph' | 'bold' | 'bullet' | 'numbered' | 'blockquote' | 'divider' | 'spacer';
  text?: string;
  num?: string;
}

function parseMarkdown(rawText: string): MarkdownBlock[] {
  const text = stripEmoji(rawText);
  const lines = text.split('\n');
  const blocks: MarkdownBlock[] = [];

  for (const line of lines) {
    if (line.startsWith('### ')) {
      blocks.push({ type: 'h3', text: line.replace(/^### /, '').replace(/\*\*/g, '') });
    } else if (line.startsWith('## ')) {
      blocks.push({ type: 'h2', text: line.replace(/^## /, '').replace(/\*\*/g, '') });
    } else if (line.startsWith('# ')) {
      blocks.push({ type: 'h1', text: line.replace(/^# /, '').replace(/\*\*/g, '') });
    } else if (line.startsWith('**') && line.endsWith('**')) {
      blocks.push({ type: 'bold', text: line.replace(/\*\*/g, '') });
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      blocks.push({ type: 'bullet', text: line.replace(/^[-*] /, '').replace(/\*\*(.*?)\*\*/g, '$1') });
    } else if (line.match(/^\d+\.\s/)) {
      const match = line.match(/^(\d+)\.\s(.*)$/);
      if (match) {
        blocks.push({ type: 'numbered', text: match[2].replace(/\*\*(.*?)\*\*/g, '$1'), num: match[1] });
      }
    } else if (line.startsWith('> ')) {
      blocks.push({ type: 'blockquote', text: line.replace(/^>\s*/, '').replace(/\*\*(.*?)\*\*/g, '$1') });
    } else if (line.match(/^---/) || line.match(/^___/)) {
      blocks.push({ type: 'divider' });
    } else if (line.trim() === '') {
      blocks.push({ type: 'spacer' });
    } else {
      blocks.push({ type: 'paragraph', text: line.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1') });
    }
  }
  return blocks;
}

const PDF_MARGINS = { top: 38, bottom: 30, left: 25, right: 25 };

function renderPageHeader(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  // Blue top bar
  doc.setFillColor(45, 125, 210);
  doc.rect(0, 0, pageWidth, 6, 'F');
  // SIT-HR label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(45, 125, 210);
  doc.text('SIT-HR', PDF_MARGINS.left, 18);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Advisory Pack', PDF_MARGINS.left + 22, 18);
  // Separator
  doc.setDrawColor(224, 224, 224);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGINS.left, 22, pageWidth - PDF_MARGINS.right, 22);
}

function renderPageFooter(doc: jsPDF, pageNum: number): void {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(224, 224, 224);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGINS.left, pageHeight - 18, pageWidth - PDF_MARGINS.right, pageHeight - 18);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('SIT-HR - System-generated HR guidance, not legal advice. Review before acting.', PDF_MARGINS.left, pageHeight - 12);
  doc.text(`Page ${pageNum}`, pageWidth - PDF_MARGINS.right, pageHeight - 12, { align: 'right' });
}

function renderBlocks(doc: jsPDF, blocks: MarkdownBlock[], startY: number, indent: number = 0): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const leftEdge = PDF_MARGINS.left + indent;
  const contentWidth = pageWidth - leftEdge - PDF_MARGINS.right;
  let y = startY;

  function needsNewPage(needed: number): boolean {
    return y + needed > pageHeight - PDF_MARGINS.bottom;
  }

  function newPage(): void {
    doc.addPage();
    renderPageHeader(doc);
    y = PDF_MARGINS.top;
  }

  for (const block of blocks) {
    switch (block.type) {
      case 'h1': {
        if (needsNewPage(20)) newPage();
        y += 6;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(15);
        doc.setTextColor(28, 28, 30);
        const lines = doc.splitTextToSize(block.text || '', contentWidth);
        doc.text(lines, leftEdge, y);
        y += lines.length * 8 + 2;
        doc.setDrawColor(45, 125, 210);
        doc.setLineWidth(0.5);
        doc.line(leftEdge, y, leftEdge + contentWidth, y);
        y += 5;
        break;
      }
      case 'h2': {
        if (needsNewPage(14)) newPage();
        y += 5;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(45, 125, 210);
        const lines = doc.splitTextToSize((block.text || '').toUpperCase(), contentWidth);
        doc.text(lines, leftEdge, y);
        y += lines.length * 6 + 3;
        break;
      }
      case 'h3': {
        if (needsNewPage(12)) newPage();
        y += 3;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(28, 28, 30);
        const lines = doc.splitTextToSize(block.text || '', contentWidth);
        doc.text(lines, leftEdge, y);
        y += lines.length * 6 + 2;
        break;
      }
      case 'paragraph': {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        const lines = doc.splitTextToSize(block.text || '', contentWidth);
        if (needsNewPage(lines.length * 5 + 2)) newPage();
        doc.text(lines, leftEdge, y);
        y += lines.length * 5 + 2;
        break;
      }
      case 'bold': {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(28, 28, 30);
        const lines = doc.splitTextToSize(block.text || '', contentWidth);
        if (needsNewPage(lines.length * 5 + 2)) newPage();
        doc.text(lines, leftEdge, y);
        y += lines.length * 5 + 2;
        break;
      }
      case 'bullet': {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        const lines = doc.splitTextToSize(block.text || '', contentWidth - 8);
        if (needsNewPage(lines.length * 5 + 2)) newPage();
        doc.setFillColor(45, 125, 210);
        doc.circle(leftEdge + 2, y - 1.5, 1, 'F');
        doc.text(lines, leftEdge + 7, y);
        y += lines.length * 5 + 1.5;
        break;
      }
      case 'numbered': {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        const lines = doc.splitTextToSize(block.text || '', contentWidth - 8);
        if (needsNewPage(lines.length * 5 + 2)) newPage();
        doc.setFont('helvetica', 'bold');
        doc.text(`${block.num}.`, leftEdge, y);
        doc.setFont('helvetica', 'normal');
        doc.text(lines, leftEdge + 7, y);
        y += lines.length * 5 + 1.5;
        break;
      }
      case 'blockquote': {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        const lines = doc.splitTextToSize(block.text || '', contentWidth - 12);
        const boxH = lines.length * 5 + 6;
        if (needsNewPage(boxH + 4)) newPage();
        y += 1;
        doc.setFillColor(240, 247, 255);
        doc.rect(leftEdge, y - 4, contentWidth, boxH, 'F');
        doc.setDrawColor(45, 125, 210);
        doc.setLineWidth(1.5);
        doc.line(leftEdge, y - 4, leftEdge, y - 4 + boxH);
        doc.text(lines, leftEdge + 6, y);
        y += boxH + 2;
        break;
      }
      case 'divider': {
        if (needsNewPage(8)) newPage();
        y += 3;
        doc.setDrawColor(224, 224, 224);
        doc.setLineWidth(0.3);
        doc.line(leftEdge, y, leftEdge + contentWidth, y);
        y += 4;
        break;
      }
      case 'spacer': {
        y += 3;
        break;
      }
    }
  }
  return y;
}

// ---------------------------------------------------------------------------
// PDF binder generation
// ---------------------------------------------------------------------------

/** Lines starting with these prefixes are metadata and should be skipped in advisory content. */
const METADATA_PREFIXES = [
  'QUERY TYPE:',
  'SECTOR FLAG:',
  'RISK RATING:',
  'LEGAL FRAMEWORK:',
  'POLICY CHECK:',
  'PROTECTED DISCLOSURE CHECK:',
  'JANUARY 2027 FLAG:',
];

function isMetadataLine(line: string): boolean {
  const trimmed = line.trim();
  return METADATA_PREFIXES.some((prefix) => trimmed.startsWith(prefix));
}

/**
 * Extract numbered action steps from an assistant message.
 * Looks for lines like "1. Do something" that appear to be action items.
 */
function extractActionSteps(content: string): string[] {
  const lines = content.split('\n');
  const steps: string[] = [];
  for (const line of lines) {
    const match = line.match(/^\d+\.\s+(.+)$/);
    if (match) {
      const text = match[1].replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1').trim();
      if (text.length > 0) {
        steps.push(text);
      }
    }
  }
  return steps;
}

/**
 * Deduplicate action steps by checking for significant overlap.
 */
function deduplicateActions(actions: string[]): string[] {
  const unique: string[] = [];
  for (const action of actions) {
    const normalized = action.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();
    const isDuplicate = unique.some((existing) => {
      const existingNorm = existing.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();
      return existingNorm === normalized || existingNorm.includes(normalized) || normalized.includes(existingNorm);
    });
    if (!isDuplicate) {
      unique.push(action);
    }
  }
  return unique;
}

function generateBinderPdf(
  messages: Message[],
  conversationTitle: string,
  caseRef: string,
  reportSummary: {
    situation_type: string;
    summary: string;
    risk_level: string;
    risk_rationale: string;
    key_legal_framework: string[];
    immediate_actions: string[];
    flags: string[];
    detailed_analysis?: {
      competing_tensions?: Array<{
        tension: string;
        obligation_a: string;
        obligation_b: string;
        resolution: string;
      }>;
      investigation_framework?: string[];
      tribunal_exposure?: {
        current: string;
        post_jan_2027: string;
        mitigation: string;
      };
      process_checklist?: string[];
    };
  },
  generatedDocs: GeneratedDoc[]
): Blob {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PDF_MARGINS.left - PDF_MARGINS.right;
  const now = new Date();
  const dateStr = formatDate(now);

  // ---- PAGE 1: COVER ----
  // Blue top bar
  doc.setFillColor(45, 125, 210);
  doc.rect(0, 0, pageWidth, 10, 'F');

  // SIT-HR title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.setTextColor(28, 28, 30);
  doc.text('SIT-HR', pageWidth / 2, 55, { align: 'center' });

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text('HR Advisory Report', pageWidth / 2, 67, { align: 'center' });

  // Case reference pill
  if (caseRef) {
    doc.setFillColor(45, 125, 210);
    const refText = caseRef;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    const refWidth = doc.getTextWidth(refText) + 14;
    doc.roundedRect(pageWidth / 2 - refWidth / 2, 82, refWidth, 10, 4, 4, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text(refText, pageWidth / 2, 89, { align: 'center' });
  } else {
    doc.setFontSize(11);
    doc.setTextColor(150, 150, 150);
    doc.text('No case reference', pageWidth / 2, 89, { align: 'center' });
  }

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated: ${dateStr}`, pageWidth / 2, 108, { align: 'center' });

  // Confidential
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(163, 45, 45);
  doc.text('CONFIDENTIAL - FOR MANAGEMENT USE ONLY', pageWidth / 2, 125, { align: 'center' });

  // Blue bottom bar
  doc.setFillColor(45, 125, 210);
  doc.rect(0, pageHeight - 6, pageWidth, 6, 'F');

  // Cover page footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('SIT-HR - System-generated HR guidance, not legal advice.', pageWidth / 2, pageHeight - 12, { align: 'center' });

  // ---- PAGE 2: SITUATION SUMMARY ----
  doc.addPage();
  renderPageHeader(doc);
  let y = PDF_MARGINS.top;

  // "Situation Summary" H1 with blue underline
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(28, 28, 30);
  doc.text('Situation Summary', PDF_MARGINS.left, y);
  y += 4;
  doc.setDrawColor(45, 125, 210);
  doc.setLineWidth(0.5);
  doc.line(PDF_MARGINS.left, y, PDF_MARGINS.left + contentWidth, y);
  y += 10;

  // Situation type badge
  if (reportSummary.situation_type) {
    const badgeText = stripEmoji(reportSummary.situation_type);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const badgeWidth = doc.getTextWidth(badgeText) + 10;
    doc.setFillColor(45, 125, 210);
    doc.roundedRect(PDF_MARGINS.left, y - 4, badgeWidth, 8, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text(badgeText, PDF_MARGINS.left + 5, y + 1);
    y += 12;
  }

  // Summary paragraph
  if (reportSummary.summary) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const summaryClean = stripEmoji(formatResponse(reportSummary.summary));
    const summaryLines = doc.splitTextToSize(summaryClean, contentWidth);
    doc.text(summaryLines, PDF_MARGINS.left, y);
    y += summaryLines.length * 5 + 6;
  }

  // Risk level badge
  if (reportSummary.risk_level) {
    const riskText = stripEmoji(reportSummary.risk_level);
    const riskUpper = riskText.toUpperCase();

    let fillR = 250, fillG = 238, fillB = 218;
    let textR = 133, textG = 79, textB = 11;

    if (riskUpper.includes('LOW')) {
      fillR = 234; fillG = 243; fillB = 222;
      textR = 59; textG = 109; textB = 17;
    } else if (riskUpper.includes('CRITICAL')) {
      fillR = 163; fillG = 45; fillB = 45;
      textR = 255; textG = 255; textB = 255;
    } else if (riskUpper.includes('HIGH')) {
      fillR = 252; fillG = 235; fillB = 235;
      textR = 163; textG = 45; textB = 45;
    }
    // Default (medium) already set above

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(60, 60, 60);
    doc.text('RISK LEVEL', PDF_MARGINS.left, y);
    y += 5;

    doc.setFontSize(11);
    const riskBadgeText = `  ${riskText}  `;
    const riskBadgeWidth = doc.getTextWidth(riskBadgeText) + 10;
    doc.setFillColor(fillR, fillG, fillB);
    doc.roundedRect(PDF_MARGINS.left, y - 5, riskBadgeWidth, 10, 3, 3, 'F');
    doc.setTextColor(textR, textG, textB);
    doc.text(riskText, PDF_MARGINS.left + 5, y + 1);
    y += 12;
  }

  // Risk rationale
  if (reportSummary.risk_rationale) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const rationaleClean = stripEmoji(reportSummary.risk_rationale);
    const rationaleLines = doc.splitTextToSize(rationaleClean, contentWidth);
    doc.text(rationaleLines, PDF_MARGINS.left, y);
    y += rationaleLines.length * 5 + 6;
  }

  // Key Legal Framework
  if (reportSummary.key_legal_framework && reportSummary.key_legal_framework.length > 0) {
    if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(45, 125, 210);
    doc.text('KEY LEGAL FRAMEWORK', PDF_MARGINS.left, y);
    y += 6;

    for (const item of reportSummary.key_legal_framework) {
      const cleanItem = stripEmoji(item);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(cleanItem, contentWidth - 8);

      if (y + lines.length * 5 + 2 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage();
        renderPageHeader(doc);
        y = PDF_MARGINS.top;
      }

      doc.setFillColor(45, 125, 210);
      doc.circle(PDF_MARGINS.left + 2, y - 1.5, 1, 'F');
      doc.text(lines, PDF_MARGINS.left + 7, y);
      y += lines.length * 5 + 1.5;
    }
    y += 4;
  }

  // Immediate Actions (numbered checklist with checkbox squares)
  if (reportSummary.immediate_actions && reportSummary.immediate_actions.length > 0) {
    if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(45, 125, 210);
    doc.text('IMMEDIATE ACTIONS', PDF_MARGINS.left, y);
    y += 6;

    for (let i = 0; i < reportSummary.immediate_actions.length; i++) {
      const item = stripEmoji(formatResponse(reportSummary.immediate_actions[i]));
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(item, contentWidth - 16);

      if (y + lines.length * 5 + 4 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage();
        renderPageHeader(doc);
        y = PDF_MARGINS.top;
      }

      // Checkbox square
      doc.setDrawColor(45, 125, 210);
      doc.setLineWidth(0.4);
      doc.rect(PDF_MARGINS.left, y - 3.5, 4, 4);

      // Number and text
      doc.setFont('helvetica', 'bold');
      doc.text(`${i + 1}.`, PDF_MARGINS.left + 6, y);
      doc.setFont('helvetica', 'normal');
      doc.text(lines, PDF_MARGINS.left + 12, y);
      y += lines.length * 5 + 3;
    }
    y += 4;
  }

  // Flags section (only if flags array is not empty)
  if (reportSummary.flags && reportSummary.flags.length > 0) {
    if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }

    // Calculate total height for flags box
    let flagsHeight = 8;
    const flagLineArrays: string[][] = [];
    for (const flag of reportSummary.flags) {
      const cleanFlag = stripEmoji(flag);
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(cleanFlag, contentWidth - 16);
      flagLineArrays.push(lines);
      flagsHeight += lines.length * 5 + 2;
    }
    flagsHeight += 4;

    if (y + flagsHeight > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }

    // Light red background box
    doc.setFillColor(252, 235, 235);
    doc.roundedRect(PDF_MARGINS.left, y - 2, contentWidth, flagsHeight, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(163, 45, 45);
    doc.text('FLAGS', PDF_MARGINS.left + 4, y + 4);
    y += 10;

    for (const lines of flagLineArrays) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(163, 45, 45);
      doc.text(lines, PDF_MARGINS.left + 8, y);
      y += lines.length * 5 + 2;
    }
    y += 6;
  }

  // ---- LEGAL ANALYSIS PAGE (High/Critical only) ----
  if (reportSummary.detailed_analysis) {
    const da = reportSummary.detailed_analysis;
    doc.addPage();
    renderPageHeader(doc);
    y = PDF_MARGINS.top;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(28, 28, 30);
    doc.text('Legal Analysis', PDF_MARGINS.left, y);
    y += 4;
    doc.setDrawColor(45, 125, 210);
    doc.setLineWidth(0.5);
    doc.line(PDF_MARGINS.left, y, PDF_MARGINS.left + contentWidth, y);
    y += 10;

    // Competing tensions
    if (da.competing_tensions && da.competing_tensions.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(45, 125, 210);
      doc.text('COMPETING LEGAL OBLIGATIONS', PDF_MARGINS.left, y);
      y += 8;

      for (const t of da.competing_tensions) {
        if (y + 35 > pageHeight - PDF_MARGINS.bottom) {
          doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
        }
        // Tension title
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(28, 28, 30);
        const tLines = doc.splitTextToSize(stripEmoji(t.tension), contentWidth);
        doc.text(tLines, PDF_MARGINS.left, y);
        y += tLines.length * 5 + 3;

        // Two columns: Obligation A vs B
        const colWidth = (contentWidth - 6) / 2;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        const aLines = doc.splitTextToSize(stripEmoji(t.obligation_a), colWidth);
        const bLines = doc.splitTextToSize(stripEmoji(t.obligation_b), colWidth);
        const maxLines = Math.max(aLines.length, bLines.length);
        doc.text(aLines, PDF_MARGINS.left, y);
        doc.text(bLines, PDF_MARGINS.left + colWidth + 6, y);
        y += maxLines * 5 + 3;

        // Resolution - blue background
        const resLines = doc.splitTextToSize(stripEmoji(t.resolution), contentWidth - 8);
        const resH = resLines.length * 5 + 8;
        if (y + resH > pageHeight - PDF_MARGINS.bottom) {
          doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
        }
        doc.setFillColor(240, 247, 255);
        doc.rect(PDF_MARGINS.left, y - 4, contentWidth, resH, 'F');
        doc.text(resLines, PDF_MARGINS.left + 4, y);
        y += resH + 4;
      }
      y += 4;
    }

    // Investigation framework
    if (da.investigation_framework && da.investigation_framework.length > 0) {
      if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(45, 125, 210);
      doc.text('KEY QUESTIONS THIS INVESTIGATION MUST ANSWER', PDF_MARGINS.left, y);
      y += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      for (let i = 0; i < da.investigation_framework.length; i++) {
        const item = stripEmoji(da.investigation_framework[i]);
        const lines = doc.splitTextToSize(item, contentWidth - 12);
        if (y + lines.length * 5 + 4 > pageHeight - PDF_MARGINS.bottom) {
          doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
        }
        doc.setDrawColor(45, 125, 210);
        doc.setLineWidth(0.4);
        doc.rect(PDF_MARGINS.left, y - 3.5, 4, 4);
        doc.setFont('helvetica', 'bold');
        doc.text(`${i + 1}.`, PDF_MARGINS.left + 6, y);
        doc.setFont('helvetica', 'normal');
        doc.text(lines, PDF_MARGINS.left + 12, y);
        y += lines.length * 5 + 3;
      }
      y += 4;
    }

    // Tribunal exposure
    if (da.tribunal_exposure) {
      if (y + 30 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(45, 125, 210);
      doc.text('TRIBUNAL EXPOSURE ANALYSIS', PDF_MARGINS.left, y);
      y += 8;

      autoTable(doc, {
        startY: y,
        head: [['Current Exposure', 'Post-January 2027', 'Mitigation']],
        body: [[
          stripEmoji(da.tribunal_exposure.current),
          stripEmoji(da.tribunal_exposure.post_jan_2027),
          stripEmoji(da.tribunal_exposure.mitigation),
        ]],
        margin: { left: PDF_MARGINS.left, right: PDF_MARGINS.right },
        styles: { fontSize: 8, font: 'helvetica', textColor: [60, 60, 60], cellPadding: 6 },
        headStyles: { fillColor: [45, 125, 210], textColor: [255, 255, 255], fontStyle: 'bold' },
        columnStyles: { 0: { cellWidth: contentWidth / 3 }, 1: { cellWidth: contentWidth / 3 }, 2: { cellWidth: contentWidth / 3 } },
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable?.finalY + 8 || y + 40;
    }

    // Process checklist
    if (da.process_checklist && da.process_checklist.length > 0) {
      if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
      }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(45, 125, 210);
      doc.text('PROCESS CHECKLIST', PDF_MARGINS.left, y);
      y += 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      for (let i = 0; i < da.process_checklist.length; i++) {
        const item = stripEmoji(da.process_checklist[i]);
        const lines = doc.splitTextToSize(item, contentWidth - 12);
        if (y + lines.length * 5 + 4 > pageHeight - PDF_MARGINS.bottom) {
          doc.addPage(); renderPageHeader(doc); y = PDF_MARGINS.top;
        }
        doc.setDrawColor(45, 125, 210);
        doc.setLineWidth(0.4);
        doc.rect(PDF_MARGINS.left, y - 3.5, 4, 4);
        doc.setFont('helvetica', 'bold');
        doc.text(`${i + 1}.`, PDF_MARGINS.left + 6, y);
        doc.setFont('helvetica', 'normal');
        doc.text(lines, PDF_MARGINS.left + 12, y);
        y += lines.length * 5 + 3;
      }
    }
  }

  // ---- ADVISORY GUIDANCE ----
  doc.addPage();
  renderPageHeader(doc);
  y = PDF_MARGINS.top;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(28, 28, 30);
  doc.text('Advisory Guidance', PDF_MARGINS.left, y);
  y += 4;
  doc.setDrawColor(45, 125, 210);
  doc.setLineWidth(0.5);
  doc.line(PDF_MARGINS.left, y, PDF_MARGINS.left + contentWidth, y);
  y += 8;

  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    if (msg.role !== 'assistant') continue;

    // Find preceding user message
    let precedingUserContent = '';
    for (let j = i - 1; j >= 0; j--) {
      if (messages[j].role === 'user') {
        precedingUserContent = messages[j].content;
        break;
      }
    }

    // Check space
    if (y + 20 > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }

    // Small grey label: "On the question of: [user message truncated to 80 chars]"
    if (precedingUserContent) {
      const truncated = stripEmoji(precedingUserContent).substring(0, 80) + (precedingUserContent.length > 80 ? '...' : '');
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      const labelLines = doc.splitTextToSize(`On the question of: ${truncated}`, contentWidth);
      doc.text(labelLines, PDF_MARGINS.left, y);
      y += labelLines.length * 4 + 3;
    }

    // Filter out metadata lines and render remaining content
    const contentLines = msg.content.split('\n');
    const filteredLines = contentLines.filter((line) => !isMetadataLine(line));
    const filteredContent = filteredLines.join('\n');

    const blocks = parseMarkdown(filteredContent);
    y = renderBlocks(doc, blocks, y, 0);
    y += 6;

    // Separator between advisory sections
    if (y + 3 > pageHeight - PDF_MARGINS.bottom) {
      doc.addPage();
      renderPageHeader(doc);
      y = PDF_MARGINS.top;
    }
    doc.setDrawColor(224, 224, 224);
    doc.setLineWidth(0.2);
    doc.line(PDF_MARGINS.left, y, pageWidth - PDF_MARGINS.right, y);
    y += 6;
  }

  // ---- ACTION CHECKLIST PAGE ----
  // Collect action steps from ALL assistant messages
  const allActions: string[] = [];
  for (const msg of messages) {
    if (msg.role === 'assistant') {
      const steps = extractActionSteps(msg.content);
      allActions.push(...steps);
    }
  }
  const uniqueActions = deduplicateActions(allActions.map((a) => stripEmoji(formatResponse(a))));

  if (uniqueActions.length > 0) {
    doc.addPage();
    renderPageHeader(doc);
    y = PDF_MARGINS.top;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(28, 28, 30);
    doc.text('Action Checklist', PDF_MARGINS.left, y);
    y += 4;
    doc.setDrawColor(45, 125, 210);
    doc.setLineWidth(0.5);
    doc.line(PDF_MARGINS.left, y, PDF_MARGINS.left + contentWidth, y);
    y += 8;

    for (let i = 0; i < uniqueActions.length; i++) {
      const item = uniqueActions[i];
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(item, contentWidth - 16);

      if (y + lines.length * 5 + 4 > pageHeight - PDF_MARGINS.bottom) {
        doc.addPage();
        renderPageHeader(doc);
        y = PDF_MARGINS.top;
      }

      // Checkbox square
      doc.setDrawColor(45, 125, 210);
      doc.setLineWidth(0.4);
      doc.rect(PDF_MARGINS.left, y - 3.5, 4, 4);

      // Number and text
      doc.setFont('helvetica', 'bold');
      doc.text(`${i + 1}.`, PDF_MARGINS.left + 6, y);
      doc.setFont('helvetica', 'normal');
      doc.text(lines, PDF_MARGINS.left + 12, y);
      y += lines.length * 5 + 3;
    }
  }

  // ---- DOCUMENTS INCLUDED PAGE ----
  if (generatedDocs.length > 0) {
    doc.addPage();
    renderPageHeader(doc);
    y = PDF_MARGINS.top;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(28, 28, 30);
    doc.text('Documents Included', PDF_MARGINS.left, y);
    y += 4;
    doc.setDrawColor(45, 125, 210);
    doc.setLineWidth(0.5);
    doc.line(PDF_MARGINS.left, y, PDF_MARGINS.left + contentWidth, y);
    y += 8;

    const tableBody = generatedDocs.map((d, i) => [
      String(i + 1),
      d.title,
      d.category,
      'Supporting document for advisory guidance',
    ]);

    autoTable(doc, {
      startY: y,
      head: [['#', 'Document', 'Category', 'Purpose']],
      body: tableBody,
      margin: { left: PDF_MARGINS.left, right: PDF_MARGINS.right },
      styles: { fontSize: 8, font: 'helvetica', textColor: [60, 60, 60] },
      headStyles: { fillColor: [45, 125, 210], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 30 },
        3: { cellWidth: 50 },
      },
    });

    // Note at bottom
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY = (doc as any).lastAutoTable?.finalY || y + 40;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Complete all [INSERT: ...] fields before use', PDF_MARGINS.left, finalY + 8);
  }

  // ---- ADD FOOTERS TO ALL PAGES ----
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i > 1) {
      renderPageFooter(doc, i - 1);
    }
  }

  return doc.output('blob');
}

// ---------------------------------------------------------------------------
// Main export function
// ---------------------------------------------------------------------------

export async function generateExportPack(
  messages: Message[],
  conversationTitle: string,
  caseRef: string,
  onProgress: (status: string) => void
): Promise<void> {
  // Step 1: Analyze conversation via AI
  onProgress('Analyzing conversation...');

  const headers = await getAuthHeaders();
  const response = await fetch('/api/chat', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      documentGeneration: true,
      conversationHistory: messages.map((m) => ({
        role: m.role,
        content: m.content,
      })),
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to analyze conversation: ${response.status}`);
  }

  const result = await response.json();

  if (result.type !== 'document_pack') {
    throw new Error('Unexpected response type from document generation endpoint');
  }

  let packData: DocumentPackData;
  try {
    packData = parseJsonSafe(result.content);
  } catch {
    throw new Error(
      'Failed to parse document pack data from AI response. The response may be malformed.'
    );
  }

  // Step 2: Fetch report summary
  onProgress('Generating report summary...');
  const summaryResponse = await fetch('/api/report-summary', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      conversationHistory: messages.map(m => ({ role: m.role, content: m.content })),
    }),
  });

  let reportSummary = {
    situation_type: 'HR Advisory',
    summary: packData.summary,
    risk_level: 'Medium',
    risk_rationale: '',
    key_legal_framework: [] as string[],
    immediate_actions: packData.actionChecklist,
    flags: [] as string[],
  };

  if (summaryResponse.ok) {
    try {
      const summaryResult = await summaryResponse.json();
      let cleaned = summaryResult.content.trim();
      const fenceMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (fenceMatch) cleaned = fenceMatch[1].trim();
      reportSummary = { ...reportSummary, ...JSON.parse(cleaned) };
    } catch {}
  }

  // Step 3: Generate DOCX files
  onProgress('Generating documents...');

  const now = new Date();
  const dateStr = formatDate(now);
  const generatedDocs: GeneratedDoc[] = [];

  for (const docSpec of packData.documents) {
    const template = getTemplateById(docSpec.templateId);
    const { generateDocxBlob } = await import('./docxGenerator');

    const blob = await generateDocxBlob({
      content: template?.sections
        ? template.sections.map(s => (s.heading ? s.heading.toUpperCase() + '\n\n' : '') + s.paragraphs.join('\n')).join('\n\n')
        : docSpec.title,
      title: docSpec.title,
      tier: 2,
      category: template?.category,
      reviewNotice: '',
      caseRef: caseRef || undefined,
      filledFields: docSpec.filledFields,
    });

    const filename = sanitizeFilename(docSpec.title) + '.docx';

    generatedDocs.push({
      filename,
      title: docSpec.title,
      category: template?.category || 'General',
      blob,
    });
  }

  // Step 4: Generate binder PDF
  onProgress('Building binder PDF...');

  const pdfBlob = generateBinderPdf(
    messages,
    conversationTitle,
    caseRef,
    reportSummary,
    generatedDocs
  );

  // Step 5: Create ZIP and trigger download
  onProgress('Creating ZIP archive...');

  const zip = new JSZip();
  zip.file('binder.pdf', pdfBlob);

  const docsFolder = zip.folder('documents');
  if (docsFolder) {
    for (const genDoc of generatedDocs) {
      docsFolder.file(genDoc.filename, genDoc.blob);
    }
  }

  const zipBlob = await zip.generateAsync({ type: 'blob' });

  const prefix = caseRef ? sanitizeFilename(caseRef) : 'SITHR-export';
  const dateFileStr = formatDateFilename(now);
  saveAs(zipBlob, `${prefix}-${dateFileStr}.zip`);
}
