-- Expand thin articles with full content
-- Run in Supabase SQL Editor

-- Bradford Factor
UPDATE news_articles SET content = E'## What the Bradford Factor Is\n\nThe Bradford Factor is a scoring formula used to measure the disruptive impact of short-term, frequent absences. Formula: B = S squared x D, where S is the number of separate absence spells and D is total days absent in a rolling 12-month period.\n\nThe key insight: frequent short absences are more disruptive than a single long absence of the same total duration. Three separate one-day absences produces a score of 27 (9 x 3). One absence of nine days produces a score of 9 (1 x 9).\n\n## Setting Thresholds\n\nOrganisations set their own trigger thresholds. A commonly used SME framework:\n\n- 0 to 49: No formal action. Welfare conversation if a pattern is emerging.\n- 50 to 149: Informal intervention. Return to work conversation and 1:1.\n- 150 to 399: Stage 1 formal. First written warning under capability route.\n- 400 to 749: Stage 2 formal. Final written warning.\n- 750 and above: Stage 3 formal. Consider dismissal with full capability process.\n\nThresholds must be written into policy and communicated to all staff before operating.\n\n## The Legal Requirements\n\n**Policy must be written and communicated.** You cannot apply trigger points to an employee who was never told the policy existed. Applying retrospectively is procedurally unfair.\n\n**Return to work conversations are mandatory before scoring.** Every absence counted must have been followed by a documented return to work conversation. An absence not followed up cannot be counted.\n\n**Disability-related absences must be excluded or discounted.** This carries the highest legal risk. Failure to discount creates exposure under s.15 EqA 2010 (discrimination arising from disability), s.19 (indirect discrimination), and ss.20-21 (failure to make reasonable adjustments). The constructive knowledge test means you may be liable even where the employee did not formally disclose.\n\n**Pregnancy-related absences must be excluded entirely.** Inclusion is pregnancy discrimination under s.18 EqA 2010.\n\n**Statutory family leave is excluded.** Maternity, paternity, adoption, shared parental, and parental bereavement leave excluded entirely.\n\n**Must be applied consistently.** Different treatment for different employees creates discrimination risk.\n\n## The Correct Process\n\n1. Write the policy with defined thresholds\n2. Issue to all staff and document communication\n3. Conduct return to work conversations for every absence\n4. At each return to work, ask about ongoing health conditions\n5. Seek OH advice where a condition is disclosed before applying thresholds\n6. Exclude disability-related absences before calculating\n7. Exclude pregnancy and statutory leave\n8. Only then apply threshold and trigger\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'bradford-factor-correct-implementation';

-- Disciplinary Five Mistakes
UPDATE news_articles SET content = E'## Why Process Matters More Than the Decision\n\nTribunals apply the range of reasonable responses test (Iceland Frozen Foods v Jones [1983]). The question is not whether the tribunal would have decided the same way - it is whether the decision fell within the range a reasonable employer might have made.\n\nAn employer can dismiss for conduct the tribunal considers minor and still win - if the process was right. An employer can dismiss for serious conduct and lose - if the process was flawed.\n\n## Mistake 1 - Same Person Investigates and Hears\n\nThe Acas Code requires separation where possible. An investigator who chairs the hearing has already formed a view. The employee senses this. Where any alternative exists - another manager, external consultant - use it. If truly unavoidable, document why.\n\n## Mistake 2 - Inadequate Investigation\n\nThe Burchell test (BHS v Burchell [1978]) requires reasonable grounds established through reasonable investigation. This means speaking to all relevant witnesses, reviewing all documents, and giving the employee a genuine opportunity to respond. An investigation that confirms a predetermined conclusion is not reasonable.\n\n## Mistake 3 - Evidence Not Provided in Advance\n\nAll evidence to be relied upon must be enclosed with the hearing invitation. The employee must have reasonable time to consider it. Five working days is the minimum. Presenting evidence at the hearing that the employee has not seen is a fundamental procedural failure.\n\n## Mistake 4 - Decision Already Made\n\nA hearing is not a formality. The employee must have a genuine opportunity to change the outcome. Where a tribunal identifies that the outcome letter was drafted before the hearing or the manager had already communicated the decision, the process fails.\n\n## Mistake 5 - No Right of Appeal\n\nThe right of appeal is fundamental. The appeal must be heard by someone not previously involved, ideally more senior. It must be a genuine reconsideration, not a rubber stamp.\n\n## The Cost\n\nAcas 25% uplift on compensatory award for procedural failures. Currently up to approximately £30,886 additional exposure. From January 2027, the uplift applies to an uncapped award.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'disciplinary-five-mistakes-tribunals';

-- Grievance Handling
UPDATE news_articles SET content = E'## The Purpose of a Grievance Procedure\n\nA grievance procedure gives employees a fair mechanism for raising concerns and employers a structured way to respond. When it works, it resolves problems before they escalate. When it does not, it becomes the foundation of a constructive dismissal claim.\n\n## The Legal Framework\n\nThe Acas Code of Practice (2015) sets the minimum standard. Failure to follow it allows a 25% uplift on compensation. The Employment Relations Act 1999 s.10 provides the right to be accompanied.\n\n## The Five Stages\n\n**Stage 1 - Receipt and acknowledgement.** Acknowledge in writing within five working days. Confirm it is being treated formally. Do not indicate a view on the merits.\n\n**Stage 2 - Investigation.** Appoint an investigator not involved in the events. Gather evidence from all relevant parties. Interview the grievant and witnesses. Review documents.\n\n**Stage 3 - Hearing.** Invite with at least five working days notice. Provide all evidence. Confirm right to be accompanied. Hear the case fully before forming a view.\n\n**Stage 4 - Decision.** Written outcome letter with findings on each element, reasoning, actions, right of appeal, and deadline. The reasoning must be genuine.\n\n**Stage 5 - Appeal.** Heard by someone different from and senior to the original decision-maker. A genuine reconsideration.\n\n## Grievance During Disciplinary\n\nOptions: suspend disciplinary while grievance is resolved, deal concurrently if different matters, or address within the hearing if connected. Document the decision with reasons.\n\n## High-Risk Scenarios\n\n**Protected disclosure elements.** Check whether any content amounts to a qualifying disclosure under PIDA 1998. Elevated legal risk requires specialist advice.\n\n**Discrimination allegations.** Investigation must be thorough and independent. External support may be appropriate.\n\n**Senior management implicated.** Independence is critical. External investigation may be the only viable approach.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'grievance-handling-procedure';

-- SSP Changes
UPDATE news_articles SET content = E'## What Changed on 6 April 2026\n\nThree fundamental changes to Statutory Sick Pay under the Employment Rights Act 2025.\n\n## Change 1 - Waiting Days Abolished\n\nPreviously SSP was not payable for the first three days. From 6 April 2026, SSP is payable from the first day of absence. Applies to sickness periods beginning on or after that date.\n\n## Change 2 - Lower Earnings Limit Removed\n\nPreviously employees needed to earn at least £123 per week to qualify. From 6 April 2026, all employees qualify regardless of earnings. This significantly expands SSP to part-time, bank, and zero hours workers.\n\n## Change 3 - Rate\n\nSSP rate from 6 April 2026: £123.25 per week or 80% of average weekly earnings, whichever is lower. Payable for up to 28 weeks.\n\nFor variable hours workers, average weekly earnings are calculated from the eight weeks before the first day of incapacity.\n\n## What Employers Need to Check\n\n**Payroll system.** Must calculate SSP from day one with no waiting period. Confirm with your provider the update has been applied.\n\n**Sickness absence policy.** Any reference to waiting days or the lower earnings limit is now out of date.\n\n**Employment contracts.** Contracts referencing waiting days or LEL eligibility need updating via variation letter.\n\n**Contractual sick pay schemes.** Where schemes reference waiting days or earnings eligibility, review whether updates are needed. Cannot pay below statutory minimum.\n\n## Fair Work Agency\n\nSSP enforcement transferred to the FWA from April 2026. Powers to investigate proactively and issue penalties for underpayment. Accurate absence records and payroll documentation are essential.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'ssp-changes-april-2026';

-- Reasonable Adjustments
UPDATE news_articles SET content = E'## The Basic Duty\n\nUnder ss.20-21 Equality Act 2010, employers must make reasonable adjustments where a provision, criterion, or practice puts a disabled person at a substantial disadvantage. Applies from day one, during recruitment, and throughout employment. No qualifying period.\n\n## Who Is Disabled\n\nPhysical or mental impairment with substantial and long-term adverse effect on day-to-day activities. Long-term means 12 months or likely to last 12 months. Progressive conditions (cancer, MS, HIV) deemed disabilities from diagnosis. Mental health conditions can qualify.\n\n## The Constructive Knowledge Test\n\nYou do not need formal disclosure to be liable. Under Schedule 8 para.20 EqA, the test is whether you knew or could reasonably have been expected to know. Multiple absences citing the same condition, informal mentions of health issues, or performance patterns consistent with a condition may create constructive knowledge (Donelien v Liberata [2018] CA).\n\n## Common Adjustments in Care\n\nAdjusted shift patterns, phased returns, modified duties, additional rest breaks, written confirmation of verbal instructions, adjusted lone working. Access to Work can fund up to 100% of costs. Many adjustments cost nothing.\n\n## The Process\n\n1. Acknowledge requests promptly in writing\n2. Do not delay obvious adjustments for perfect evidence\n3. Seek OH advice for complex situations\n4. Consider a range of adjustments in consultation\n5. Document reasoning for any declined adjustment\n6. Implement and set review date\n\n## High-Risk Scenarios\n\nDelaying adjustments that would facilitate return from absence. Ignoring mental health disclosures. Not reviewing progressive conditions. Disciplining for performance without considering disability. Inconsistent responses to similar requests.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'reasonable-adjustments-day-one-duty';

-- Zero Hours
UPDATE news_articles SET content = E'## The Current Position\n\nZero hours contracts are lawful. Workers have the same basic rights - NMW, holiday pay, discrimination protection - but hours can vary to zero. Exclusivity clauses are prohibited and unenforceable.\n\n## What the Employment Rights Act 2025 Introduces\n\nRight to guaranteed hours for eligible workers. Not yet in force - secondary legislation required. Workers regularly working consistent hours over a reference period will be entitled to a contract offer reflecting those hours. Monitor GOV.UK for commencement.\n\n## What Is Already Required\n\n**Holiday pay.** Must reflect average earnings from 52 weeks (or weeks worked if less). Includes overtime and regular supplements. Rolled-up holiday pay reintroduced for irregular hours workers under WTR amendments.\n\n**Annual leave records.** From 6 April 2026, records must be kept for all workers including zero hours. Six years retention. Criminal offence for failure.\n\n**NMW for all hours.** Every hour worked at or above NMW. Includes time required to be available. Travel between service users counts as working time.\n\n**Written statement.** Right to written statement of particulars since April 2020.\n\n## Worker Status\n\nZero hours contract does not automatically determine legal status. Long-standing bank workers with consistent hours may have acquired employee status through working pattern regardless of contract label. Periodic review recommended.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'zero-hours-contracts-2026';

-- Protected Disclosures
UPDATE news_articles SET content = E'## What Is a Protected Disclosure\n\nA communication disclosing information the worker reasonably believes tends to show: criminal offence, breach of legal obligation, miscarriage of justice, danger to health and safety, environmental damage, deliberate concealment, or (from April 2026) sexual harassment. Must be in the public interest.\n\nThe worker does not need to be right. They need reasonable belief.\n\n## Why This Matters in Care\n\nCare settings create frequent situations where protection may apply without anyone realising it. Staffing concerns affecting service user safety. Documenting colleague non-compliance with care plans. Raising concerns about own safety on lone working shifts.\n\nThe method does not matter. A WhatsApp message can be a protected disclosure. An informal verbal comment can qualify.\n\n## Section 100 ERA 1996\n\nSeparate protection for employees who leave or refuse to work in circumstances of serious and imminent danger. Automatically unfair dismissal, no qualifying period, uncapped compensation.\n\nIn care: a support worker who leaves citing safety concerns has a potential s.100 defence. Whether objectively reasonable is relevant but does not remove protection.\n\n## The Critical Distinction\n\nWhere safety concerns preceded the incident being investigated:\n1. Did the worker have a genuine belief in danger?\n2. Did they follow correct procedure?\n\nIf (1) yes and (2) no - disciplinary is about the procedure breach, not the concern itself. Framing dismissal as being about the decision to leave rather than procedure failure is vulnerable to s.100 challenge.\n\n## Consequences\n\nAutomatically unfair under s.103A (whistleblowing) and s.100 (health and safety): no qualifying period, compensation uncapped, interim relief available.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'protected-disclosures-care-sector';

-- Constructive Dismissal
UPDATE news_articles SET content = E'## What Constructive Dismissal Is\n\nOccurs when an employee resigns in response to a fundamental breach of contract by the employer (ERA 1996 s.95(1)(c)). Treated as dismissal for tribunal purposes.\n\n## The Legal Test (Western Excavating v Sharp [1978])\n\n1. Employer committed a fundamental breach of contract\n2. Employee resigned in response to that breach\n3. Employee did not affirm the breach by continuing to work unreasonably long after discovering it\n\nThe most common basis is the implied term of mutual trust and confidence (Malik v BCCI [1997]): neither party may act to destroy or seriously damage the relationship of trust and confidence.\n\n## How It Arises\n\n**Sustained management conduct.** Pattern of excessive criticism, public humiliation, exclusion. Cumulative effect breaches trust and confidence even where no single act is fundamental.\n\n**Unilateral changes.** Imposing significant changes to hours, pay, role, or location without consent.\n\n**Failure to address grievances.** Not investigating or responding properly to a formal grievance.\n\n**Failure to address harassment.** Awareness of harassment by a colleague without reasonable steps to address it.\n\n## The Last Straw\n\nA series of acts where the final act - even minor - is the last straw entitling resignation. The series taken together must amount to a trust and confidence breach. An employer with a history of poor management may face a claim in response to something they consider trivial.\n\n## Qualifying Period\n\nCurrently 2 years for ordinary constructive unfair dismissal. From January 2027: 6 months. Constructive dismissal risk increases significantly after that date for employees in their first two years.\n\nNo qualifying period for discrimination, whistleblowing, or pregnancy-related constructive dismissal.\n\n## ET Time Limits\n\nCurrently 3 months less one day from resignation. Extending to 6 months less one day from October 2026.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'constructive-dismissal-explained';

-- Documentation
UPDATE news_articles SET content = E'## The Documentation Problem in Care\n\nManagers work operationally. Supervision gets deprioritised. Informal concerns go unwritten. By the time a formal process begins, the record is thin.\n\nAt tribunal, that thin record works against the employer. Not because decisions were wrong - but because there is no evidence they were made fairly through proper process.\n\n## What Good Documentation Looks Like\n\n**Supervision records.** Monthly for new starters, quarterly minimum for established staff. Date, topics, concerns, actions, signatures. Five minutes to write.\n\n**Return to work records.** Every absence. Reason, health condition check, fitness, adjustments, Bradford Factor status.\n\n**File notes.** Any significant conversation. Date, present, discussed, agreed. Not formal - contemporaneous.\n\n**Incident records.** Dual purpose: safeguarding and HR evidence. A pattern of incidents involving one worker is relevant to subsequent formal process. If not recorded, the pattern cannot be evidenced.\n\n## Consistency\n\nMust be applied consistently across all staff. Meticulous records for the dismissed employee and nothing for comparable employees implies selective management and discrimination. The test is whether a reasonable employer would have treated this employee the same as others.\n\n## Building the Habit\n\nSimple, low-friction systems that managers actually use. Brief templates. Consistent storage. Applied from day one of every employment relationship - not starting only when problems emerge. Documentation that begins when trouble starts looks like evidence-gathering. Documentation maintained throughout looks like good management.\n\n---\n\nThis article provides general guidance based on the law as at April 2026.'
WHERE slug = 'supervision-documentation-defence';
